export const spaces = [
  {
    id: 1,
    name: "Sala de Reuniões 1",
    description: "Sala de reuniões do 1º andar",
    capacity: 10,
  },
  {
    id: 2,
    name: "Sala de Reuniões 2",
    description: "Sala de reuniões do 2º andar",
    capacity: 12,
  },
  {
    id: 3,
    name: "Sala de Reuniões 3",
    description: "Sala de reuniões do 3º andar",
    capacity: 8,
  },
  {
    id: 4,
    name: "Sala de Reuniões 4",
    description: "Sala de reuniões do 4º andar",
    capacity: 15,
  },
  {
    id: 5,
    name: "Sala de Conferência A",
    description: "Sala ampla de conferências",
    capacity: 25,
  },
  {
    id: 6,
    name: "Auditório Central",
    description: "Auditório principal",
    capacity: 100,
  },
  {
    id: 7,
    name: "Sala de Treinamento 1",
    description: "Espaço para treinamento no 1º andar",
    capacity: 20,
  },
  {
    id: 8,
    name: "Sala de Reuniões VIP",
    description: "Sala de reuniões para executivos",
    capacity: 6,
  },
  {
    id: 9,
    name: "Sala de Workshop",
    description: "Espaço para workshops",
    capacity: 18,
  },
  {
    id: 10,
    name: "Sala de Apresentações",
    description: "Sala para apresentações e eventos",
    capacity: 40,
  },
  {
    id: 11,
    name: "Laboratório de TI",
    description: "Laboratório de tecnologia",
    capacity: 20,
  },
  {
    id: 12,
    name: "Sala de Projetos",
    description: "Espaço para trabalho em projetos",
    capacity: 12,
  },
  {
    id: 13,
    name: "Sala de Planejamento",
    description: "Sala de planejamento estratégico",
    capacity: 8,
  },
  {
    id: 14,
    name: "Sala de Reuniões 5",
    description: "Sala de reuniões do 5º andar",
    capacity: 10,
  },
  {
    id: 15,
    name: "Estúdio de Gravação",
    description: "Espaço para gravações e podcasts",
    capacity: 4,
  },
  {
    id: 16,
    name: "Espaço de Coworking",
    description: "Área colaborativa de trabalho",
    capacity: 15,
  },
  {
    id: 17,
    name: "Sala de Ideias",
    description: "Espaço para brainstorms e ideias",
    capacity: 8,
  },
  {
    id: 18,
    name: "Sala de Apresentação 2",
    description: "Segunda sala para apresentações",
    capacity: 35,
  },
  {
    id: 19,
    name: "Auditório Secundário",
    description: "Auditório de apoio",
    capacity: 80,
  },
  {
    id: 20,
    name: "Sala de Conferência B",
    description: "Sala ampla de conferências",
    capacity: 30,
  },
  {
    id: 21,
    name: "Sala de Treinamento 2",
    description: "Espaço para treinamento no 2º andar",
    capacity: 22,
  },
  {
    id: 22,
    name: "Sala de Reunião Informal",
    description: "Espaço para reuniões descontraídas",
    capacity: 6,
  },
  {
    id: 23,
    name: "Laboratório de Inovação",
    description: "Espaço para inovação e criação",
    capacity: 16,
  },
  {
    id: 24,
    name: "Sala de Reuniões 6",
    description: "Sala de reuniões do 6º andar",
    capacity: 10,
  },
  {
    id: 25,
    name: "Sala de Reuniões 7",
    description: "Sala de reuniões do 7º andar",
    capacity: 12,
  },
  {
    id: 26,
    name: "Sala de Reuniões 8",
    description: "Sala de reuniões do 8º andar",
    capacity: 14,
  },
  {
    id: 27,
    name: "Sala de Reuniões 9",
    description: "Sala de reuniões do 9º andar",
    capacity: 15,
  },
  {
    id: 28,
    name: "Sala de Reuniões 10",
    description: "Sala de reuniões do 10º andar",
    capacity: 8,
  },
  {
    id: 29,
    name: "Sala de Reuniões 11",
    description: "Sala de reuniões do 11º andar",
    capacity: 10,
  },
  {
    id: 30,
    name: "Sala de Reuniões 12",
    description: "Sala de reuniões do 12º andar",
    capacity: 12,
  },
  {
    id: 31,
    name: "Sala de Reuniões 13",
    description: "Sala de reuniões do 13º andar",
    capacity: 14,
  },
  {
    id: 32,
    name: "Sala de Reuniões 14",
    description: "Sala de reuniões do 14º andar",
    capacity: 8,
  },
  {
    id: 33,
    name: "Sala de Reuniões 15",
    description: "Sala de reuniões do 15º andar",
    capacity: 10,
  },
  {
    id: 34,
    name: "Sala de Reuniões 16",
    description: "Sala de reuniões do 16º andar",
    capacity: 12,
  },
  {
    id: 35,
    name: "Sala de Reuniões 17",
    description: "Sala de reuniões do 17º andar",
    capacity: 10,
  },
  {
    id: 36,
    name: "Sala de Reuniões 18",
    description: "Sala de reuniões do 18º andar",
    capacity: 8,
  },
  {
    id: 37,
    name: "Sala de Conferência C",
    description: "Sala ampla de conferências",
    capacity: 28,
  },
  {
    id: 38,
    name: "Sala de Projetos Avançados",
    description: "Espaço para projetos avançados",
    capacity: 20,
  },
  {
    id: 39,
    name: "Auditório Compacto",
    description: "Auditório compacto para eventos menores",
    capacity: 50,
  },
  {
    id: 40,
    name: "Laboratório Criativo",
    description: "Espaço para desenvolvimento criativo",
    capacity: 10,
  },
  {
    id: 41,
    name: "Sala de Ideação",
    description: "Espaço para brainstorming",
    capacity: 8,
  },
  {
    id: 42,
    name: "Estúdio de Vídeo",
    description: "Espaço para gravação de vídeos",
    capacity: 5,
  },
  {
    id: 43,
    name: "Sala de Reuniões 19",
    description: "Sala de reuniões do 19º andar",
    capacity: 10,
  },
  {
    id: 44,
    name: "Sala de Reuniões 20",
    description: "Sala de reuniões do 20º andar",
    capacity: 12,
  },
  {
    id: 45,
    name: "Sala de Conferência D",
    description: "Sala de conferência",
    capacity: 24,
  },
  {
    id: 46,
    name: "Espaço de Estudos",
    description: "Área para estudo e pesquisa",
    capacity: 15,
  },
  {
    id: 47,
    name: "Laboratório de Robótica",
    description: "Espaço de robótica",
    capacity: 12,
  },
  {
    id: 48,
    name: "Sala de Inovação Tecnológica",
    description: "Espaço para inovação em tecnologia",
    capacity: 14,
  },
  {
    id: 49,
    name: "Sala de Conferência E",
    description: "Sala ampla de conferências",
    capacity: 32,
  },
  {
    id: 50,
    name: "Sala de Reuniões 21",
    description: "Sala de reuniões do 21º andar",
    capacity: 10,
  },
  {
    id: 51,
    name: "Sala de Reuniões 22",
    description: "Sala de reuniões do 22º andar",
    capacity: 12,
  },
];
