services:
  backend:
    container_name: wise.rooms.backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  db:
    container_name: wise.rooms.db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
