export enum AuditAction {
  RESERVATION_CREATE = "RESERVATION_CREATE",
  RESERVATION_UPDATE = "RESERVATION_UPDATE",
  RESERVATION_DELETE = "RESERVATION_DELETE",
  SPACE_CREATE = "SPACE_CREATE",
  SPACE_UPDATE = "SPACE_UPDATE",
  SPACE_DELETE = "SPACE_DELETE",
  ITEM_CREATE = "ITEM_CREATE",
  ITEM_UPDATE = "ITEM_UPDATE",
  ITEM_DELETE = "ITEM_DELETE",
  SPACE_ITEM_CREATE = "SPACE_ITEM_CREATE",
  SPACE_ITEM_UPDATE = "SPACE_ITEM_UPDATE",
  SPACE_ITEM_DELETE = "SPACE_ITEM_DELETE",
}
