export enum EResourceType {
  PROJECTOR = "PROJECTOR",
  WHITEBOARD = "WHITEBOARD",
  MONITOR = "MONITOR",
  PRINTER = "PRINTER",
  SPEAKER = "SPEAKER",
  MICROPHONE = "MICROPHONE",
  COMPUTER = "COMPUTER",
  TELEPHONE = "TELEPHONE",
  INTERNET = "INTERNET",
  OTHER = "OTHER",
}
