export enum PermissionType {
  CAN_VIEW_RESERVATIONS = "CAN_VIEW_RESERVATIONS",
  CAN_MANAGE_RESERVATIONS = "CAN_MANAGE_RESERVATIONS",
  CAN_MANAGE_SPACES = "CAN_MANAGE_SPACES",
  CAN_MANAGE_ITEMS = "CAN_MANAGE_ITEMS",
  CAN_MANAGE_SPACE_ITEMS = "CAN_MANAGE_SPACE_ITEMS",
}
